### PR TITLE
Adding in frontend app

### PR DESCRIPTION
**Pull request by syedhali**
## Trello
- https://trello.com/c/e6bXDWAX/40-serve-up-react-ui-components-using-django-app

## Summary
This PR adds a new app to the herbridge project (`frontend`) that will be used to implement the frontend UI spec'ed out here: https://gallery.io/projects/MCHbtQVoQ2HCZe_5CoPFrW-T/files/MCHbtQVoQ2HCZY2ohRFERFa4. 

The frontend will be using React so this PR includes all the necessary work required to compile those React components into a single js file that is then used by a Django template. I've added a README in the frontend directory with instructions for how other devs can get their dev flow setup (including support for hot reloading). 

I've also included the [material-ui](https://material-ui.com/) framework so we can utilize those components instead of building everything from scratch (this was the original intent of the designs on gallery).

### CODE REVIEW

**Comment by mradamcox** [comment]
I tried putting this on our staging server, but got a couple of errors when running `npm install`.

```
UNMET DEPENDENCY @material-ui/core@^3.0.2
UNMET PEER DEPENDENCY jss@^9.7.0
```

Trying to install those packages individually led to errors that indicate issues with Ubuntu. I'm not familiar node at all, and can't put time into debugging this right now, but just a heads up.

**Comment by syedhali** [comment]
@mradamcox what version of npm are you running?

**Comment by syedhali** [comment]
@khanlou yup it's generated anytime you run `npm run build` or `npm run dev`. It might make sense to exclude this file from git and have a postinstall npm script that will build this file so these PRs are smaller.

**Comment by syedhali** [comment]
@mradamcox I was able to get it all installing in my Ubuntu vagrant box by running:
```
sudo npm install --unsafe-perm=true --allow-root
```

I'm not 100% sudo is needed since I think that's a weird artifact from vagrant.  I'm guessing you're also going to need to update `node` and `npm`. 

### Updating Node
Do this first before updating npm! 
```
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
```

### Updating NPM
```
curl -L https://www.npmjs.com/install.sh | sudo sh
```

If this fails it's because there are some cached resources from the previous npm installation that's causing the issue. Try removing the node_modules folder and installing npm again via:
```
rm -rf /usr/local/lib/node_modules
sudo npm install -g npm@latest
```

**Pull request merged**
